# Generated by Django 5.0 on 2024-01-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_currency'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('currency', 'name')},
        ),
    ]
